# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 # node server.js from script

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'  # Path to your test result files
    testRunTitle: 'SuccotashDB Tests'
    testRunner: 'JUnit'  # Use 'JUnit' as the test runner for JUnit-style reports
    testFailureThreshold: '20'
    targetPath: '$(System.DefaultWorkingDirectory)/test-results' 

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install express sequelize mysql2 body-parser cors
   
  displayName: 'npm install and build'  
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- script: |
    ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'List Contents of Artifact Staging Directory'

- script: |
    npm install -g @vue/cli
    npm install
    npm run build
  displayName: 'Frontend build and test'
  workingDirectory: $(Build.SourcesDirectory)/vue-3-frontend

